name: "setup-uv-env"
description: "Composite action to setup the Python and uv environment."

inputs:
  python-version:
    required: false
    description: "The Python version to use."
    default: "3.8"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v1

    - name: Set up Python environment with uv
      run: uv venv
      shell: bash

    - name: Install the project
      run: uv sync --extra dev
      shell: bash

    - name: Run tests
      run: uv tooÙ… run pytest vuid/tests.py
      shell: bash
