name: release-main

on:
  workflow_dispatch:
  release:
    types: [published]
    branches: [master]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up the environment
        uses: ./.github/actions/setup-uv-env

      - name: Export tag
        id: vars
        run: echo tag=${GITHUB_REF#refs/*/} >> $GITHUB_OUTPUT

      - name: Build and publish
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          PIPY_TOKEN: ${{ secrets.PIPY_TOKEN }}
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          pip install twine
          make build-and-publish
  deploy-docs:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up the environment
        uses: ./.github/actions/setup-uv-env

      - name: Deploy documentation
        run: uv tool run mkdocs gh-deploy --force
